### PR TITLE
Added classes and id support to asciimath

### PR DESCRIPTION
**Pull request by saivan**
This commit adds class and id support, which allows for interesting
things like scaling scaling a part of an equation or animating
parts of the expression as well as applying arbitrary (supported)
styles to different parts of expressions.

### CODE REVIEW

**Comment by drlippman** [comment]
I haven't tested it yet, but looking at the code it looks like a good approach. My only suggestion might be to replace the complicated ternary with a switch or set of if-else statements, just for readability and ease of future extensions.

**Comment by saivan** [comment]
Sure thing, I'll do that

**Comment by saivan** [comment]
Does it all look in order now @drlippman?

**Comment by drlippman** [comment]
Looks great!  Got it merged after copying the changes over to the jax.js file and adding a test to the unittests.js file for it.

**Comment by saivan** [comment]
Awesome :)

**Pull request closed without merging**
