### PR TITLE
Add \bowtie, \ltimes and \rtimes equivalent asciimath codes

### PR DESCRIPTION
**Pull request by adius**
Really useful for relational algebra!

### CODE REVIEW

**Comment by drlippman** [comment]
I'd love to hear Peter's thoughts on this.  He had expressed concerns years ago about adding too many symbols to the core symbol set, partly because AsciiMath was intended to be simple and partly for efficiency.

**Comment by adius** [comment]
Ok. Then we should mention him properly…
@jipsen

**Comment by jipsen** [comment]
My concern was that the core symbols in AsciiMath are supposed to resemble the actual output (and be easy to type). Adding lots of such symbols can have unintended side effects since it modifies the parser and can cause changes to how existing pages render if they upgrade to a version with new symbols. E.g. if one uses |><| for \bowtie and |>< for \ltimes, then any page that happens to contain these ascii sequences with render differently.

However there are at least two ways in which my concerns would not by valid. 

1. If all TeX/LaTeX symbols (or all MathJax symbols) were allowed, that would not be a problem since they are escaped with a "\". AsciiMath already makes quite a few of them accessible, so why not cover them all? Efficiency is not a pressing concern if the implementation is done well (e.g. as in MathJax or KaTeX). The file size would increase, but JavaScript file size is not a big concern anymore.

2. Each user can of course add their own symbols by associating an ascii string with a unicode character/string using "define" or "newcommand" http://www1.chapman.edu/~jipsen/mathml/asciimathextend.html. (This should probably be mentioned on the asciimath.org main page.) In essence this allows user-defined macros, and we could make a package of such symbols that users can add to their page if they find the core symbol set to restrictive. In this case the main AsciiMath file will not casue any changes in rendering, but anyone who needs more symbols can try such a predefined package and see if it works well for them.

Any preferences on how to proceed? Of course these two suggestions could both be implemented simultaneously, and there may well be other good possibilities.

**Comment by drlippman** [comment]
For your first point, doesn't AsciiMath ignore the backslash, so for example 2\times4 and 2times4 are equivalent?  In that case, adding TeX symbols could have the same side effect you were worried about;  `rtimesq` would no longer be interpreted the same as `r xx q`.  Personally, I'm not too concerned about that since people really should put spaces between symbols IMHO, but might there be some TeX symbols where this could be an issue? 


     On Monday, June 1, 2015 1:30 PM, Peter Jipsen <notifications@github.com> wrote:
   

 My concern was that the core symbols in AsciiMath are supposed to resemble the actual output (and be easy to type). Adding lots of such symbols can have unintended side effects since it modifies the parser and can cause changes to how existing pages render if they upgrade to a version with new symbols. E.g. if one uses |><| for \bowtie and |>< for \ltimes, then any page that happens to contain these ascii sequences with render differently.However there are at least two ways in which my concerns would not by valid.    
   - If all TeX/LaTeX symbols (or all MathJax symbols) were allowed, that would not be a problem since they are escaped with a "\". AsciiMath already makes quite a few of them accessible, so why not cover them all? Efficiency is not a pressing concern if the implementation is done well (e.g. as in MathJax or KaTeX). The file size would increase, but JavaScript file size is not a big concern anymore.
   - Each user can of course add their own symbols by associating an ascii string with a unicode character/string using "define" or "newcommand" http://www1.chapman.edu/~jipsen/mathml/asciimathextend.html. (This should probably be mentioned on the asciimath.org main page.) In essence this allows user-defined macros, and we could make a package of such symbols that users can add to their page if they find the core symbol set to restrictive. In this case the main AsciiMath file will not casue any changes in rendering, but anyone who needs more symbols can try such a predefined package and see if it works well for them.
Any preferences on how to proceed? Of course these two suggestions could both be implemented simultaneously, and there may well be other good possibilities.—

**Comment by drlippman** [comment]
Out of curiosity, who has commit and merge-pull-request rights on this repository now?  Because I don't appear to anymore.

**Comment by jipsen** [comment]
Hi David,

As far as I can tell, Peter Krautzberger and I are owners of the asciimath organization.
There are two repositories: asciimathml and asciimath.github.io
You were(are) a member of the asciimath.github.io repo, and now I just added you also as a member to the ascimathml repository. 
(It seems like you must have been a member in the past, but that’s not how it looked at this point.)

Anyway, try again to see if you now have commit and merge-pull-request rights. (I won’t pretend to fully understand the access rights structure of github, so if its not working, we may need to involve Peter K. here.)

Regards,
Peter Jipsen

**Comment by pkra** [comment]
> Out of curiosity, who has commit and merge-pull-request rights on this repository now? Because I don't appear to anymore.

Sorry about that. I'm guessing your access was lost when we moved the repo from the MathJax organization to the asciimath one.

**Pull request merged**
