### PR TITLE
Fix issues with negative alone in sub/superscripts

### LINKED ISSUE #114: Parenthesis in 'u_(-)' to avoid unexpected rendering
`u_-` needs to be written `u_(-)`to be rendered as thought
whereas `u_+` can be written as is to be rendered correctly

Indeed `u_- + 2 + u_+ + 3` is rendered such a way

and needs to be written `u_(-) + 2 + u_+ + 3` to be rendered as expected (by me only?)

- [x] Is this a bug?
- [x] When parenthesis can be omitted exactly?

### PR DESCRIPTION
**Pull request by drlippman**
Potentially fixes #114. 

Adjust so `u_-3` continues to render as u_(-3), but so
`u_- 3`  will render as u_(-1) 3

Also will fix `2^- +3` so it displays as 2^(-) + 3 instead of as 2^(-+) 3

### CODE REVIEW

**Comment by drlippman** [comment]
This potential fix uses a space to allow the user to indicate the negative shouldn't stay attached to the next symbol.

Also means `3/-4` will continue to display as `3/(-4)`, but `3/- 4` would display as `3/(-) 4`

**Comment by sebi5361** [comment]
Do you consider to maintain other files such as `ASCIIMathTeXImg.js` to reflect the changes you made in `ASCIIMathML.js`?

**Comment by drlippman** [comment]
Good catch, thanks.  I'll get those updated too.

**Comment by sebi5361** [comment]
Wouldn't it be handy to host an official js server-side asciimath to tex converter as well? (an npm package?)

Currently I use a slightly modified version of `ASCIIMathTeXImg.js` to achieve this where basically the few `window.translate = translate` expressions have been replaced by `module.exports.translate = translate` expressions.

**Comment by drlippman** [comment]
I don't use Node or npm often, so don't know how to do this.  You are welcome to take this on.

FWIW, there is a [asciimath to latex](https://www.npmjs.com/package/asciimath-to-latex) converter in npm already, though I'm not sure if it's being actively maintained.

**Comment by sebi5361** [comment]
There are a few packages out there indeed. I was thinking of having an official one in the main asciimath repo, which would get maintained together with the rest.
I am not a programmer, at most a tinkerer, but I will give it a shot. I need to:
- [ ]  Understand if transforming `window` expressions into `module.export` expressions is all that needs to be done, based on https://github.com/yuwash/asciimathml-pandocfilter current `ASCIIMathTeXImg.js` file.
- [ ] Adjust the the current official `ASCIIMathTeXImg.js`.
And eventually:
- [ ] Understand how to publish a npm package
- [ ] Make this new file available as a npm package.

**Pull request merged**
